// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unbvphckomexdatbqmnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuYnZwaGNrb21leGRhdGJxbW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTU2ODgsImV4cCI6MjA2Nzc5MTY4OH0.kwgBEolRcdKVMPkmFRoFD67pstxaRdRtIiEulPc8Et4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});